package GUI;
import Model.*;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Montse R.Zamorano
 */
public class BadconsequenceView extends javax.swing.JPanel {
    private BadConsequence bcView;
    /**
     * Creates new form BadconsequenceVIew
     */
    public BadconsequenceView() {
        initComponents();
    }
    
    public void setBadConsequence(BadConsequence bc){
        bcView = bc;
        //texto
        text.setText(bcView.getText());
        //niveles
        levelsText.setText(Integer.toString(bcView.getLevels()));
        //Muerte
        if(bcView.kills())
            deathText.setText("Estás muerto");
        else{
            deathText.setText("");
        }
        //número tesoros ocultos y visibles
        if(bcView.getnHiddenTreasures() != 0)          
            numberHidden.setText("Pierdes " 
                    + Integer.toString(bcView.getnHiddenTreasures()) + " tesoros ocultos.");
        else{
            numberHidden.setText("");
        }
        if(bcView.getnVisibleTreasures() != 0)          
            numberVisible.setText("Pierdes " 
                    + Integer.toString(bcView.getnVisibleTreasures()) + " tesoros visibles.");
        else{
            numberVisible.setText("");
        }
        //tesoros específicos
        String hid = null;
        if(!bcView.getSpecificHiddenTreasures().isEmpty()){
            hid = "Tesoros ocultos esspecíficos:";
            for(TreasureKind t :bcView.getSpecificHiddenTreasures()){
                if(t == TreasureKind.ARMOR)
                    hid+="\nArmadura";
                if(t == TreasureKind.BOTHHANDS)
                    hid+="\nAmbas manos";
                if(t == TreasureKind.HELMET)
                    hid+="\nCasco";
                if(t == TreasureKind.NECKLACE)
                    hid+="\nCollar";
                if(t == TreasureKind.ONEHAND)
                    hid+="\nMano";
                if(t == TreasureKind.SHOE)
                    hid+="\nCalzado";
            }
            
        }
        else{
            hid = "No hay tesoros ocultos específicos";
        }
        
        String vis = null;
        if(!bcView.getSpecificVisibleTreasures().isEmpty()){
            vis = "Tesoros visibles específicos: ";
            for(TreasureKind t :bcView.getSpecificVisibleTreasures()){
                if(t == TreasureKind.ARMOR)
                    vis+="\nArmadura";
                if(t == TreasureKind.BOTHHANDS)
                    vis+="\nAmbas manos";
                if(t == TreasureKind.HELMET)
                    vis+="\nCasco";
                if(t == TreasureKind.NECKLACE)
                    vis+="\nCollar";
                if(t == TreasureKind.ONEHAND)
                    vis+="\nMano";
                if(t == TreasureKind.SHOE)
                    vis+="\nCalzado";
            }
            
        }
        else{
            vis = "No hay tesoros visibles específicos";
        }
        
        specificH.setText(hid);
        specificV.setText(vis);
        
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        levels = new javax.swing.JLabel();
        levelsText = new javax.swing.JLabel();
        deathText = new javax.swing.JLabel();
        numberVisible = new javax.swing.JLabel();
        numberHidden = new javax.swing.JLabel();
        specificV = new javax.swing.JLabel();
        specificH = new javax.swing.JLabel();

        text.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        text.setText("text");

        levels.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        levels.setText("Niveles:");

        levelsText.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        levelsText.setText("levelsText");

        deathText.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        deathText.setText("deathText");

        numberVisible.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        numberVisible.setText("numberVisible");

        numberHidden.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        numberHidden.setText("numberHidden");

        specificV.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        specificV.setText("specificV");

        specificH.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        specificH.setText("specificH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specificH)
                    .addComponent(specificV)
                    .addComponent(numberHidden)
                    .addComponent(numberVisible)
                    .addComponent(deathText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(levels)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(levelsText))
                    .addComponent(text))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levels)
                    .addComponent(levelsText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deathText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberVisible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberHidden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specificH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deathText;
    private javax.swing.JLabel levels;
    private javax.swing.JLabel levelsText;
    private javax.swing.JLabel numberHidden;
    private javax.swing.JLabel numberVisible;
    private javax.swing.JLabel specificH;
    private javax.swing.JLabel specificV;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
