package GUI;
import Model.*;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author montse
 */
public class BadConsequenceView extends javax.swing.JFrame {
    private BadConsequence bcView;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
  
    public void setBadConsequence(BadConsequence bc){
        bcView = bc;
        //texto
        text.setText(bcView.getText());
        //niveles
        levelsText.setText(Integer.toString(bcView.getLevels()));
        //Muerte
        if(bcView.kills())
            deathText.setText("Sí");
        else{
            deathText.setText("No");
        }
        //número tesoros ocultos y visibles
        numberHidden.setText(Integer.toString(bcView.getnHiddenTreasures()));
        numberVisible.setText(Integer.toString(bcView.getnVisibleTreasures()));
        //tesoros específicos
        String hid = null;
        if(!bcView.getSpecificHiddenTreasures().isEmpty()){
            hid = "TESOROS OCULTOS ESPECÍFICOS";
            for(TreasureKind t :bcView.getSpecificHiddenTreasures()){
                if(t == TreasureKind.ARMOR)
                    hid+="\nArmadura";
                if(t == TreasureKind.BOTHHANDS)
                    hid+="\nAmbas manos";
                if(t == TreasureKind.HELMET)
                    hid+="\nCasco";
                if(t == TreasureKind.NECKLACE)
                    hid+="\nCollar";
                if(t == TreasureKind.ONEHAND)
                    hid+="\nMano";
                if(t == TreasureKind.SHOE)
                    hid+="\nCalzado";
            }
            
        }
        else{
            hid = "No hay tesoros ocultos específicos";
        }
        
        String vis = null;
        if(!bcView.getSpecificVisibleTreasures().isEmpty()){
            vis = "TESOROS VISIBLES ESPECÍFICOS";
            for(TreasureKind t :bcView.getSpecificVisibleTreasures()){
                if(t == TreasureKind.ARMOR)
                    vis+="\nArmadura";
                if(t == TreasureKind.BOTHHANDS)
                    vis+="\nAmbas manos";
                if(t == TreasureKind.HELMET)
                    vis+="\nCasco";
                if(t == TreasureKind.NECKLACE)
                    vis+="\nCollar";
                if(t == TreasureKind.ONEHAND)
                    vis+="\nMano";
                if(t == TreasureKind.SHOE)
                    vis+="\nCalzado";
            }
            
        }
        else{
            vis = "No hay tesoros visibles específicos";
        }
        
        specificH.setText(hid);
        specificV.setText(vis);
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levels = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        numberVisible = new javax.swing.JLabel();
        numberHidden = new javax.swing.JLabel();
        death = new javax.swing.JLabel();
        visibleText = new javax.swing.JLabel();
        levelsText = new javax.swing.JLabel();
        hiddenText = new javax.swing.JLabel();
        deathText = new javax.swing.JLabel();
        specificV = new javax.swing.JLabel();
        specificH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        levels.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        levels.setText("Niveles:");

        text.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        text.setText("Texto:");

        numberVisible.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        numberVisible.setText("Número de tesoros visibles:");

        numberHidden.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        numberHidden.setText("Número de tesoros ocultos:");

        death.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        death.setText("Muerte:");

        visibleText.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        visibleText.setText("jLabel2");

        levelsText.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        levelsText.setText("jLabel3");

        hiddenText.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        hiddenText.setText("jLabel4");

        deathText.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        deathText.setText("jLabel5");

        specificV.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        specificV.setText("Especificos visibles");

        specificH.setFont(new java.awt.Font("Skia", 0, 14)); // NOI18N
        specificH.setText("Específicos ocultos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(specificH)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(specificV)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberVisible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(visibleText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(levels)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(levelsText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(death)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deathText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberHidden)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hiddenText)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(text)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levels)
                    .addComponent(levelsText))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberVisible)
                    .addComponent(visibleText))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberHidden)
                    .addComponent(hiddenText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(death)
                    .addComponent(deathText))
                .addGap(18, 18, 18)
                .addComponent(specificV)
                .addGap(18, 18, 18)
                .addComponent(specificH)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BadConsequenceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BadConsequenceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BadConsequenceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BadConsequenceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BadConsequenceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel death;
    private javax.swing.JLabel deathText;
    private javax.swing.JLabel hiddenText;
    private javax.swing.JLabel levels;
    private javax.swing.JLabel levelsText;
    private javax.swing.JLabel numberHidden;
    private javax.swing.JLabel numberVisible;
    private javax.swing.JLabel specificH;
    private javax.swing.JLabel specificV;
    private javax.swing.JLabel text;
    private javax.swing.JLabel visibleText;
    // End of variables declaration//GEN-END:variables
}
